-- CRIAÇÃO DAS TABELAS DO SISTEMA DE CORREÇÃO

-- 1. Tabela de Escolas
create table public.escolas (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nome text not null
);

-- 2. Tabela de Turmas
create table public.turmas (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nome text not null,
  escola_id bigint references public.escolas(id) on delete cascade
);

-- 3. Tabela de Alunos
create table public.alunos (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nome text not null,
  matricula text,
  email text,
  turma_id bigint references public.turmas(id) on delete set null
);

-- 4. Tabela de Provas
create table public.provas (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  titulo text not null,
  data_aplicacao date,
  turma_id bigint references public.turmas(id) on delete cascade
);

-- 5. Tabela de Questões
create table public.questoes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  numero int,
  enunciado text,
  gabarito text, -- A, B, C, D, E
  valor decimal(5,2) default 1.0,
  prova_id bigint references public.provas(id) on delete cascade
);

-- 6. Tabela de Respostas dos Alunos
create table public.respostas_alunos (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  aluno_id bigint references public.alunos(id) on delete cascade,
  questao_id bigint references public.questoes(id) on delete cascade,
  resposta_aluno text, -- A, B, C, D, E
  unique(aluno_id, questao_id) -- Garante apenas uma resposta por questão por aluno
);

-- 7. Dados de Exemplo (Seed Data) para Teste Rápido
-- Inserir Escola
insert into public.escolas (nome) values ('Escola Exemplo');

-- Inserir Turma (assumindo ID 1 para a escola criada acima)
insert into public.turmas (nome, escola_id) values ('Turma 101', 1);

-- Inserir Aluno (assumindo ID 1 para a turma criada acima)
insert into public.alunos (nome, matricula, turma_id) values ('João da Silva', '2024001', 1);

-- Inserir Prova (assumindo ID 1 para a turma criada acima)
insert into public.provas (titulo, data_aplicacao, turma_id) values ('Prova de Matemática - 1º Bimestre', '2024-05-20', 1);

-- Inserir Questões (assumindo ID 1 para a prova criada acima)
insert into public.questoes (numero, enunciado, gabarito, prova_id) values 
(1, 'Quanto é 2 + 2?', 'B', 1),
(2, 'Qual a capital do Brasil?', 'C', 1),
(3, 'Qual a cor do céu?', 'A', 1),
(4, 'Raiz quadrada de 16?', 'D', 1),
(5, 'Dia da independência?', 'E', 1);
